#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -d /var/lib/rainloop ]; then
            if [ $(id -u www-data 2>&1 >/dev/null) ]; then
                chown -R www-data:www-data /var/lib/rainloop
            fi;
        fi;
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
